title: Nabhan Website
author: Nabhan Mazid
email: nmazid@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  This is my awesome website.
theme: minima

# social links
twitter_username: N/A # DO NOT include the @ character, or else the build will fail!
github_username:  nmazid # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
